/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentes;

/**
 *
 * @author Calderon
 */
public class PanelRecordaorios extends javax.swing.JPanel {

    /**
     * Creates new form PanelRecordaorios
     */
    public PanelRecordaorios() {
        initComponents();
        rec.escribir("Recordatorio");
        fecha.escribir("dd/mm/aaaa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new componentes.TextField();
        textField2 = new componentes.TextField();
        textField3 = new componentes.TextField();
        textField4 = new componentes.TextField();
        panelRecordatorio1 = new componentes.PanelRecordatorio();
        rec = new componentes.Etiquetas();
        fecha = new componentes.Etiquetas();

        setBackground(new java.awt.Color(255, 255, 255));

        rec.setText("etiquetas3");

        fecha.setText("etiquetas4");

        javax.swing.GroupLayout panelRecordatorio1Layout = new javax.swing.GroupLayout(panelRecordatorio1);
        panelRecordatorio1.setLayout(panelRecordatorio1Layout);
        panelRecordatorio1Layout.setHorizontalGroup(
            panelRecordatorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecordatorio1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(rec, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRecordatorio1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        panelRecordatorio1Layout.setVerticalGroup(
            panelRecordatorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecordatorio1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rec, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRecordatorio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRecordatorio1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.Etiquetas fecha;
    private componentes.PanelRecordatorio panelRecordatorio1;
    private componentes.Etiquetas rec;
    private componentes.TextField textField1;
    private componentes.TextField textField2;
    private componentes.TextField textField3;
    private componentes.TextField textField4;
    // End of variables declaration//GEN-END:variables
}
