/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentes;

import java.awt.Color;
import java.awt.Font;
import proyecto.Principal;
import static proyecto.Utils.blanco;
import static proyecto.Utils.teal;

/**
 *
 * @author Calderon
 */
public class Toolbar extends javax.swing.JPanel {

    /**
     * Creates new form Toolbar
     */
    public Toolbar() {
        initComponents();
        this.setBackground(teal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonRegresar1 = new componentes.BotonRegresar();

        setBackground(new java.awt.Color(0, 153, 51));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        jLabel1.setToolTipText("");

        botonRegresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegresar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresar1MouseClicked
        new Principal().setVisible(true);
    }//GEN-LAST:event_botonRegresar1MouseClicked

    public void removerICono(){
        botonRegresar1.remove(botonRegresar1);
    }
            
    
    public void setTitle(String title){
        jLabel1.setText(title);
        jLabel1.setFont(new Font("Monospaced", Font.BOLD , 30));
        jLabel1.setForeground(blanco);
    }
    
    public void setColor(Color newColor){
        this.setBackground(newColor);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.BotonRegresar botonRegresar1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
